### ISSUE TITLE
macro1.c should ignore parentheses in comments

### ISSUE THREAD

**Issue by jblang** [simh/simtools#7]
According the MACRO-1 docs, constant syllables are defined by parentheses, but obviously this should not be the case if the parentheses appear inside a comment from / to end of line.  It appears that macro1.c is not ignoring them, though.

I am trying to assemble the source for the famous MIT display hacks available here: http://bitsavers.trailing-edge.com/bits/DEC/pdp1/from_peter_samson/dpys5.mac

I get all kinds of confusing errors about undefined symbols and illegal expressions.  Inspection of the listing output suggests that it is attempting to parse the comments. 

When the parens are removed from the following comments, the source assembles cleanly:

line 6: / (uses TW)
line 15: / (uses no switches)
line 258: / (uses TW)

I'm attaching the [errors](https://github.com/simh/simtools/files/1264628/errors.txt) and [listing output](https://github.com/simh/simtools/files/1264633/dpys5-lst.txt).

I haven't yet studied the macro1 code long enough to understand how it works; if I have time, I will try to develop a patch and submit a pull request.  I decided to go ahead and file the bug in the hopes that someone more familiar with the code than I will beat me to it.

**Comment by markpizz** [comment]
Please fix the problem and submit a pull request.

**Comment by jblang** [comment]
I think I misdiagnosed this.  The file I was using had strange line-endings using only CR instead of CR+LF or LF.  I didn't notice before because the editor I was using displayed it normally, but it was apparent when I opened the file in vi, and when I converted all the CR chars to LF, it assembled correctly. 

I was looking at what it would take to recognize only CR as a valid line ending, and I'm a little unsure of what all I would need to change.  I think '\r' needs to be added to the ISEND macro on line 175, but I think that might break other parts of the code like line 1906, which handles CR+LF endings, and possibly other places that look for '\r' or '\n'.

**Comment by markpizz** [comment]
Well, surely the original file didn't actually have bare CR line endings.  They were probably introduced when that file was once used on a very old Mac environment.


If you really wanted to produce an error/warning about this case, where files are opened, you could read a line with fgets and look for an LF.  If none was found you could emit a warning about this file and in either case rewind the file and continue.  The first message emitted would provide insight to the user about his problem.

**Comment by jblang** [comment]
`¯\_(ツ)_/¯` I downloaded the files again directly from http://bitsavers.trailing-edge.com/bits/DEC/pdp1/from_peter_samson/ just to be sure, and all the .mac files in that directory are that way.  I will see about adding a warning when I get a chance.

**Comment by jblang** [comment]
Pull request created.

**Comment by jblang** [comment]
Closing this since the initial report was misleading and the discussion on line endings has moved to the pull request.
